# https://github.com/NixOS/nixos-artwork/blob/35ebbbf01c3119005ed180726c388a01d4d1100c/logo/README.md#L5
name: ❄️ Darwin
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-nix-darwin.yml'
      - '**.nix'
      - 'flake.*'
      - 'pkgs/lima/**'
      - 'pkgs/lima-full/**'
      - 'overlays/default.nix'
  pull_request:
    paths:
      - '.github/workflows/ci-nix-darwin.yml'
      - '**.nix'
      - 'flake.*'
      - 'pkgs/lima/**'
      - 'pkgs/lima-full/**'
      - 'overlays/default.nix'
    types: [opened, synchronize, reopened, labeled]
  schedule:
    # Every 10:42 JST
    - cron: '42 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tasks:
    if: >-
      github.event_name != 'pull_request' ||
      github.event.action == 'labeled' && github.event.label.name == 'ci-darwin' ||
      (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'ci-darwin')) ||
      (
        github.event.action != 'labeled' &&
        (
          contains(github.event.pull_request.changed_files, '**.nix') ||
          contains(github.event.pull_request.changed_files, 'flake.lock') ||
          contains(github.event.pull_request.changed_files, '.github/workflows/ci-nix-darwin.yml')
        )
      )
    defaults:
      run:
        shell: nix develop --command bash -eu -o pipefail {0}
    runs-on: macos-15-intel
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Measure nix shell initialization time
        run: echo 'This step should be done before any other "nix develop" steps'
      - run: task ci-darwin

  build:
    if: >-
      github.event_name != 'pull_request' ||
      github.event.action == 'labeled' && github.event.label.name == 'ci-darwin' ||
      (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'ci-darwin')) ||
      (
        github.event.action != 'labeled' &&
        (
          contains(github.event.pull_request.changed_files, 'pkgs/lima/') ||
          contains(github.event.pull_request.changed_files, 'pkgs/lima-full/') ||
          contains(github.event.pull_request.changed_files, 'overlays/default.nix') ||
          contains(github.event.pull_request.changed_files, 'flake.lock') ||
          contains(github.event.pull_request.changed_files, '.github/workflows/ci-nix-darwin.yml')
        )
      )
    strategy:
      fail-fast: false
      matrix:
        pname:
          - rclone
          - lima-full
    runs-on: macos-15-intel
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build package
        run: nix build .#${{ matrix.pname }}
      - name: Run passthru tests
        # Use nix-build via flake-compat for simpler recursive building of attribute sets.
        run: nix-build -A packages.x86_64-darwin.${{ matrix.pname }}.passthru.tests
